### PR TITLE
upgrade to 1.6.0 mac build of phantomjs

### PR DESCRIPTION
**Pull request by ghost**
we updated to phantomjs 1.6.0

### CODE REVIEW

**Comment by maxwell** [comment]
awesome, thanks!

**Comment by pivotaltracker** [comment]
## In replies all text above this line is added to the ticket

[Pivotal Tracker Support #8469] Request received: Re: [phantomjs-mac] upgrade to 1.6.0 mac build of phantomjs (#1)

Thanks so much for contacting Pivotal Tracker support! Your request (#8469) has been received, and is being reviewed by our support staff. 

In the mean time, you're welcome to check out our help section at https://www.pivotaltracker.com/help or join the conversation in our community at http://community.pivotaltracker.com/

To review the status of the request and add additional comments, follow the link below:
http://pivotaltracker.zendesk.com/tickets/8469

---

Maxwell Salzberg, Jul 17 15:52 (PDT)

awesome, thanks!

---

Reply to this email directly or view it on GitHub:
https://github.com/maxwell/phantomjs-mac/pull/1#issuecomment-7051975

## 

## 

---

This email is a service from Pivotal Tracker Support

**Comment by maxwell** [comment]
do you need me to push a new version of the gem?  Let me know any I will.

**Comment by pivotaltracker** [comment]
## In replies all text above this line is added to the ticket

[Pivotal Tracker Support #8470] Request received: Re: [phantomjs-mac] upgrade to 1.6.0 mac build of phantomjs (#1)

Thanks so much for contacting Pivotal Tracker support! Your request (#8470) has been received, and is being reviewed by our support staff. 

In the mean time, you're welcome to check out our help section at https://www.pivotaltracker.com/help or join the conversation in our community at http://community.pivotaltracker.com/

To review the status of the request and add additional comments, follow the link below:
http://pivotaltracker.zendesk.com/tickets/8470

---

Maxwell Salzberg, Jul 17 15:52 (PDT)

do you need me to push a new version of the gem?  Let me know any I will.

---

Reply to this email directly or view it on GitHub:
https://github.com/maxwell/phantomjs-mac/pull/1#issuecomment-7051986

## 

## 

---

This email is a service from Pivotal Tracker Support

**Pull request merged**
